const detailsData = {
    riskPointSet: [
        { name: '检查单位', value: 'checkCompanyName' },
        { name: '检查岗位', value: 'checkWorkName' },
        { name: '检查周期', value: 'checkCycle' },
        { name: '周期数量', value: 'cycleNumber' },
        { name: '下次检查日期', value: 'nextCheckTime' },
        { name: '每月执行日1', value: 'day1' },
        { name: '每月执行日2', value: 'day2' },
        { name: '周一执行', value: 'monday', isBoolean: true },
        { name: '周二执行', value: 'tuesday', isBoolean: true },
        { name: '周三执行', value: 'wednesday', isBoolean: true },
        { name: '周四执行', value: 'thursday', isBoolean: true },
        { name: '周五执行', value: 'friday', isBoolean: true },
        { name: '周六执行', value: 'saturday', isBoolean: true },
        { name: '周日执行', value: 'sunday', isBoolean: true }
    ],
    riskPointCheck: [
        { name: '工单日期', value: 'orderTime' },
        { name: '截至日期', value: 'orderStopTime' },
        { name: '所在单位', value: 'riskPointCompany' },
        { name: '地点', value: 'location' },
        { name: '检查岗位', value: 'checkWorkName' },
        { name: '检查单位', value: 'checkCompanyName' },
        { name: '是否下整改通知单', value: 'dangerListConfirm' },
        { name: '问题描述', value: 'questionDescription' },
        { name: '整改措施', value: 'correctiveMeasures' },
        { name: '处置人', value: 'disposePeople' },
        { name: '执行人', value: 'implementPeople' },
        { name: '复查人', value: 'reviewPeople' },
        { name: '整改截止日期', value: 'deadTime' },
        { name: '整改期限', value: 'correctivePeriod' },
        { name: '隐患分类', value: 'hazardClassification' },
        { name: '隐患分级', value: 'hazardLevel' }
    ],
    riskPointSearch: [
        { name: '工单日期', value: 'orderTime' },
        { name: '截至日期', value: 'orderStopTime' },
        { name: '检查岗位', value: 'checkWorkName' },
        { name: '检查人', value: 'checkPeople' },
        { name: '检查时间', value: 'checkTime' },
        { name: '单据状态', value: 'orderStatus' },
        { name: '是否下隐患单', value: 'dangerListConfirm' },
        { name: '整改处置人', value: 'disposePeople' },
        { name: '整改执行人', value: 'implementPeople' },
        { name: '整改确认人', value: 'reviewPeople' },
        { name: '整改期限', value: 'correctivePeriod' },
        { name: '整改截止日期', value: 'deadTime' },
        { name: '问题描述', value: 'questionDescription' },
        { name: '整改措施', value: 'correctiveMeasures' },
        { name: '隐患分类', value: 'hazardClassification' },
        { name: '隐患分级', value: 'hazardLevel' }
    ],
    riskPointListSearch: [
        { name: '工单日期', value: 'orderTime' },
        { name: '截至日期', value: 'orderStopTime' },
        { name: '地点', value: 'location' },
        { name: '单位', value: 'checkCompanyName' },
        { name: '检查岗位', value: 'checkWorkName' },
        { name: '检查人', value: 'checkPeople' },
        { name: '检查时间', value: 'checkTime' },
        { name: '单据状态', value: 'orderStatus' },
        { name: '是否下隐患单', value: 'dangerListConfirm' },
        { name: '整改处置人', value: 'disposePeople' },
        { name: '整改执行人', value: 'implementPeople' },
        { name: '整改确认人', value: 'reviewPeople' },
        { name: '整改期限', value: 'correctivePeriod' },
        { name: '整改截止日期', value: 'deadTime' },
        { name: '问题描述', value: 'questionDescription' },
        { name: '整改措施', value: 'correctiveMeasures' }
    ],
    outsourcedUnitSubmit: [
        { name: '外委队名称', value: 'outsourceUnitName' },
        { name: '施工单位', value: 'constructionUnit' },
        { name: '单位类型', value: 'unitType' },
        { name: '单位地点', value: 'unitLocation' },
        { name: '负责人', value: 'unitPrincipal' },
        { name: '联系人', value: 'unitContact' },
        { name: '联系方式', value: 'unitInformation' },
        { name: '工程名称', value: 'projectName' },
        { name: '施工人数', value: 'constructionNumber' },
        { name: '工程负责人', value: 'projectPrinciple' },
        { name: '计划开始时间', value: 'startDate' },
        { name: '计划结束时间', value: 'stopDate' },
        { name: '状态', value: 'requestStatus' }
    ],
    outsourcedUnitAnhuanBaowei: [
        { name: '外委队名称', value: 'outsourceUnitName' },
        { name: '签约单位', value: 'contractUnit' },
        { name: '施工单位', value: 'constructionUnit' },
        { name: '单位类型', value: 'unitType' },
        { name: '单位地点', value: 'unitLocation' },
        { name: '负责人', value: 'unitPrincipal' },
        { name: '联系人', value: 'unitContact' },
        { name: '联系方式', value: 'unitInformation' },
        { name: '工程名称', value: 'projectName' },
        { name: '施工人数', value: 'constructionNumber' },
        { name: '工程负责人', value: 'projectPrinciple' },
        { name: '计划开始时间', value: 'startDate' },
        { name: '计划结束时间', value: 'stopDate' },
        { name: '提交人', value: 'submitter' }
    ],
    outsourcedUnitProcess: [
        { name: '工程名称', value: 'projectName' },
        { name: '外委单位', value: 'outsourceUnitName' },
        { name: '签约单位', value: 'contractingUnit' },
        { name: '施工单位', value: 'projectStatus' },
        { name: '计划开始时间', value: 'planStartTime' },
        { name: '计划结束时间', value: 'planStopTime' },
        { name: '开始时间', value: 'startDate' },
        { name: '结束时间', value: 'stopDate' },
        { name: '工程内容', value: 'projectContent' },
        { name: '施工情况', value: 'constructionStatus' }
    ],
    threeViolationSubmit: [
        { name: '三违人员', value: 'personFullName' },
        { name: '三违日期', value: 'violationDate' },
        { name: '三违地点', value: 'violationPlace' },
        { name: '反思检查人', value: 'reflectCheckSubmitter' },
        { name: '班长谈话人', value: 'monitorSubmitter' },
        { name: '车间主任谈话人', value: 'workshopSubmitter' },
        { name: '工会主席谈话人', value: 'unionSubmitter' },
        { name: '支部书记谈话人', value: 'secretarySubmitter' },
        { name: '分管领导谈话人', value: 'leaderSubmitter' }
    ],
    leaderTalkFeedback: [
        { name: '日期', value: 'violationDate' },
        { name: '三违人员', value: 'violator' },
        { name: '地点', value: 'violationPlace' },
        { name: '违章行为', value: 'illegal' },
        { name: '班长谈话', value: 'monitorStatus' },
        { name: '车间主任谈话', value: 'workshopStatus' },
        { name: '工会主席谈话', value: 'unionStatus' },
        { name: '支部书记谈话', value: 'secretaryStatus' },
        { name: '分管领导谈话', value: 'leaderStatus' }
    ],
    passRecordCheck: [
        { name: '安全补课内容', value: 'safetyLessonStatus' },
        { name: '安全补课反馈时间', value: 'safetyLessonSubmitTime' },
        { name: '反思检查内容', value: 'reflectCheckStatus' },
        { name: '反思检查反馈时间', value: 'reflectCheckSubmitTime' },
        { name: '班长谈话内容', value: 'monitorStatus' },
        { name: '班长谈话谈话人', value: 'monitorSubmitter' },
        { name: '班长谈话反馈时间', value: 'monitorSubmitTime' },
        { name: '车间主任谈话内容', value: 'workshopStatus' },
        { name: '车间主任谈话谈话人', value: 'workshopSubmitter' },
        { name: '车间主任谈话反馈时间', value: 'workshopSubmitTime' },
        { name: '支部书记谈话内容', value: 'secretaryStatus' },
        { name: '支部书记谈话谈话人', value: 'secretarySubmitter' },
        { name: '支部书记谈话反馈时间', value: 'secretarySubmitTime' },
        { name: '工会主席谈话内容', value: 'unionStatus' },
        { name: '工会主席谈话谈话人', value: 'unionSubmitter' },
        { name: '工会主席谈话反馈时间', value: 'unionSubmitTime' },
        { name: '分管领导谈话内容', value: 'leaderStatus' },
        { name: '分管领导谈话谈话人', value: 'leaderSubmitter' },
        { name: '分管领导谈话反馈时间', value: 'leaderSubmitTime' },
        { name: '家属协管内容', value: 'familyManagementStatus' },
        { name: '家属协管反馈时间', value: 'familyManagementSubmitTime' }
    ],
    performanceMaintain: [
        { name: '一级要素', value: 'primaryElement' },
        { name: '二级要素', value: 'secondaryElement' },
        { name: '评价要点', value: 'evaluationPoints' },
        { name: '评价细则', value: 'evaluationRules' },
        { name: '标准分值', value: 'standardScore' },
        { name: '评分', value: 'score' },
        { name: '存在问题', value: 'question' },
        { name: '扣分情况', value: 'deductions' }
    ],
    workshop: [
        { name: '工号', value: 'workNum' },
        { name: '名称', value: 'name' },
        { name: '性别', value: 'gender' },
        { name: '身份证号', value: 'idNumber' },
        { name: '职务', value: 'position' },
        { name: '岗位工种', value: 'jobs' },
        { name: '查询范围', value: 'operatingRange' },
        { name: '所在班组', value: 'teamName' },
        { name: '整改人级别', value: 'correctorLevel' },
        { name: '复查人级别', value: 'reviewerLevel' },
        { name: '责任人级别', value: 'responsibleLevel' },
        { name: '风险排查级别', value: 'riskLevel' },
        { name: '防护设施检查级别', value: 'protectionLevel' },
        { name: '排查是否拍照', value: 'checkWhetherPhoto' },
        { name: '参加工作时间', value: 'workTime' },
        { name: '接触职业危害时间', value: 'hazardTime' },
        { name: '危害因素', value: 'hazardousFactors' },
        { name: '是否管理员', value: 'isAdmin' },
        { name: '外委单位检查人', value: 'outsourcedUnitInspection' },
        { name: '三违处理人', value: 'threeViolationHandler' },
        { name: '反思检查提交人', value: 'reflectionSubmitter' },
        { name: '班长谈话人', value: 'monitor' },
        { name: '车间主任谈话人', value: 'workshopTalker' },
        { name: '工会主席谈话人', value: 'unionTalker' },
        { name: '支部书记谈话人', value: 'branchTalker' },
        { name: '分管领导谈话人', value: 'chargeTalker' },
        { name: '非常规作业管理人', value: 'unconventionalManager' }
    ],
    riskCheckStandard: [
        { name: '序号', value: 'number' },
        { name: '地点', value: 'place' },
        { name: '设备设施/作业活动', value: 'equipment' },
        { name: '排查岗位', value: 'positionCheck' },
        { name: '危险源', value: 'riskSource' },
        { name: '危害因素', value: 'riskfactors' },
        { name: '事故后果', value: 'consequences' },
        { name: '固有等级l', value: 'inherentRankL' },
        { name: '固有等级e', value: 'inherentRankE' },
        { name: '固有等级c', value: 'inherentRankC' },
        { name: '固有等级d', value: 'inherentRankD' },
        { name: '固有等级', value: 'inherentRank' },
        { name: '技术措施', value: 'technicalMeasures' },
        { name: '管理措施', value: 'managermentMeasures' },
        { name: '教育措施', value: 'educationalMeasures' },
        { name: '个体防护措施', value: 'personalProtectiveMeasures' },
        { name: '应急措施', value: 'emergencyMeasures' },
        { name: '管控后等级l', value: 'rectificationLevelL' },
        { name: '管控后等级e', value: 'rectificationLevelE' },
        { name: '管控后等级c', value: 'rectificationLevelC' },
        { name: '管控后等级d', value: 'rectificationLevelD' },
        { name: '管控后等级', value: 'rectificationLevel' },
        { name: '管控责任人', value: 'responsiblePerson' }
    ],
    riskCheckStandard1: [
        { name: '序号', value: 'number' },
        { name: '级别', value: 'level' },
        { name: '周期', value: 'cycle' },
        { name: '是否执行', value: 'execute', isBoolean: true },
        { name: '周一', value: 'monday', isBoolean: true },
        { name: '周二', value: 'tuesday', isBoolean: true },
        { name: '周三', value: 'wednesday', isBoolean: true },
        { name: '周四', value: 'thursday', isBoolean: true },
        { name: '周五', value: 'friday', isBoolean: true },
        { name: '周六', value: 'saturday', isBoolean: true },
        { name: '周日', value: 'sunday', isBoolean: true },
        { name: '早班', value: 'morning', isBoolean: true },
        { name: '中班', value: 'noon', isBoolean: true },
        { name: '夜班', value: 'night', isBoolean: true },
        { name: '白班', value: 'twoMorning', isBoolean: true },
        { name: '晚班', value: 'twoNight', isBoolean: true },
        { name: '正常班', value: 'longMorning', isBoolean: true },
        { name: '月日期1', value: 'monthDate1' },
        { name: '月日期2', value: 'monthDate2' },
        { name: '月日期3', value: 'monthDate3' },
        { name: '下次检查日期', value: 'nextCheckDate' }
    ],
    riskCheckRecord: [
        { name: '下达时间', value: 'hiddenDate' },
        { name: '设施与风险点', value: 'riskPoint' },
        { name: '处理措施', value: 'dealMeasure' },
        { name: '整改执行人', value: 'changerExecutor', isBoolean: true },
        { name: '整改复查人', value: 'reviewer', isBoolean: true },
        { name: '是否制定整改方案', value: 'rectificationPlan', isBoolean: true },
        { name: '整改期限', value: 'rectificationPeriod', isBoolean: true },
        { name: '状态', value: 'recordStatus', isBoolean: true },
        { name: '处罚金额', value: 'penaltyAmount', isBoolean: true },
        { name: '隐患分类', value: 'hiddenClassification', isBoolean: true },
        { name: '隐患级别', value: 'hiddenLevel', isBoolean: true },
        { name: '隐患地点', value: 'hiddenPlace', isBoolean: true },
        { name: '责任单位', value: 'dutyUnit', isBoolean: true },
        { name: '隐患内容', value: 'hiddenContent' },
        { name: '整改情况', value: 'changeStatus' },
        { name: '整改时间', value: 'changeCompeteTime' },
        { name: '处置人', value: 'responsible' },
        { name: '处置时间', value: 'disposalTime' }
    ],
    hiddenDangerRecord: [
        { name: '隐患日期', value: 'hiddenDate' },
        { name: '隐患地点', value: 'hiddenPlace' },
        { name: '责任单位', value: 'dutyUnit' },
        { name: '责任人', value: 'responsible' },
        { name: '处理状态', value: 'recordStatus' },
        { name: '隐患分类', value: 'hiddenClassification' },
        { name: '隐患类型', value: 'hiddenType' },
        { name: '隐患分级', value: 'hiddenLevel' },
        { name: '上报级别', value: 'reportLevel' },
        { name: '隐患内容', value: 'hiddenContent' },
        { name: '处理措施', value: 'dealMeasure' },
        { name: '要求整改日期', value: 'reviseDate' },
        { name: '整改执行人', value: 'changerExecutor' },
        { name: '整改日期', value: 'reviseDate' },
        { name: '整改情况', value: 'changeStatus' },
        { name: '复查人', value: 'reviewer' },
        { name: '复查日期', value: 'reviewDate' },
        { name: '责任班组', value: 'responsibleTeam' },
        { name: '处罚金额', value: 'penaltyAmount' },
        { name: '设施及风险点', value: 'riskPoint' }
    ],
    specialEquipmentMaintain: [
        { name: '注册编号', value: 'zcbh' },
        { name: '设备名称', value: 'sbmc' },
        { name: '规格型号', value: 'ggxh' },
        { name: '安装地点', value: 'azdd' },
        { name: '设备代码', value: 'sbdm' },
        { name: '用途', value: 'yt' },
        { name: '使用状态', value: 'syzt' },
        { name: '生产单位', value: 'scdw' },
        { name: '出厂日期', value: 'ccrq' },
        { name: '检验状态', value: 'jyzt' },
        { name: '上次检验日期', value: 'scjyrq' },
        { name: '下次检验日期', value: 'xcjyrq' },
        { name: '是否超期', value: 'sfcq' },
        { name: '技术参数', value: 'jscs' },
        { name: '所属车间', value: 'cjmc' },
        { name: '种类', value: 'zl' },
        { name: '类别', value: 'lb' },
        { name: '品种', value: 'pz' },
        { name: '出厂编号', value: 'ccbh' },
        { name: '安装时间', value: 'azsj' },
        { name: '安装地点', value: 'azdd' },
        { name: '安装单位', value: 'azdw' },
        { name: '投运日期', value: 'tyrq' },
        { name: '注册编号', value: 'zcbh' },
        { name: '责任人', value: 'zrr' },
        { name: '检验报告编号', value: 'jybbbh' },
        { name: '检验周期', value: 'jyzq' },
        { name: '检验机构', value: 'jyjg' },
        { name: '检验前自检结论', value: 'jyqzjjl' },
        { name: '实际检验情况', value: 'sjjyqk' },
        { name: '检验整改情况', value: 'jyzgqk' },
        { name: '检验机构检验结论', value: 'jgjyjl' },
        { name: '备注', value: 'bz' }
    ]
}
export default detailsData
