// 视图组件
const view = {
  tabs: () => import('@/layouts/tabs'),
  blank: () => import('@/layouts/BlankView')
}

// 路由组件注册
const routerMap = {
  root: { path: '/', redirect: 'login', component: view.tabs },
  login: { path: "login", component: () => import('@/views/login/login') },
  statisticsCompany: { component: () => import('@/views/statistics/statisticsCompany') },
  statisticsBranch: { component: () => import('@/views/statistics/statisticsBranch') },
  statisticsWorkshop: { component: () => import('@/views/statistics/statisticsWorkshop') },
  resumption: { component: view.blank },
  resumptionSet: { component: () => import('@/views/resumption/resumptionSet') },
  resumptionSubmit: { component: () => import('@/views/resumption/resumptionSubmit') },
  resumptionSearch: { component: () => import('@/views/resumption/resumptionSearch') },
  riskPoint: { component: view.blank },
  riskPointSet: { component: () => import('@/views/riskPoint/riskPointSet') },
  riskPointCheck: { component: () => import('@/views/riskPoint/riskPointCheck') },
  riskPointSearch: { component: () => import('@/views/riskPoint/riskPointSearch') },
  riskPointListSearch: { component: () => import('@/views/riskPoint/riskPointListSearch') },
  majorInsception: { component: view.blank },
  majorInsceptionSet: { component: () => import('@/views/majorInsception/majorInsceptionSet') },
  majorInsceptionSubmit: { component: () => import('@/views/majorInsception/majorInsceptionSubmit') },
  majorInsceptionSearch: { component: () => import('@/views/majorInsception/majorInsceptionSearch') },
  majorInsceptionCollect: { component: () => import('@/views/majorInsception/majorInsceptionCollect') },
  weekly: { component: view.blank },
  weeklyWrite: { component: () => import('@/views/weekly/weeklyWrite') },
  weeklyCollect: { component: () => import('@/views/weekly/weeklyCollect') },
  weeklySearch: { component: () => import('@/views/weekly/weeklySearch') },
  outsourcedUnit: { component: view.blank },
  outsourcedUnitSubmit: { component: () => import('@/views/outsourcedUnit/outsourcedUnitSubmit') },
  outsourcedUnitAnhuan: { component: () => import('@/views/outsourcedUnit/outsourcedUnitAnhuan') },
  outsourcedUnitBaowei: { component: () => import('@/views/outsourcedUnit/outsourcedUnitBaowei') },
  outsourcedUnitUpload: { component: () => import('@/views/outsourcedUnit/outsourcedUnitUpload') },
  outsourcedUnitConfirm: { component: () => import('@/views/outsourcedUnit/outsourcedUnitConfirm') },
  outsourcedUnitProcessManage: { component: () => import('@/views/outsourcedUnit/outsourcedUnitProcessManage') },
  outsourcedUnitAssess: { component: () => import('@/views/outsourcedUnit/outsourcedUnitAssess') },
  outsourcedUnitFileManage: { component: () => import('@/views/outsourcedUnit/outsourcedUnitFileManage') },
  outsourcedUnitProcessSearch: { component: () => import('@/views/outsourcedUnit/outsourcedUnitProcessSearch') },
  outsourcedUnitFileSearch: { component: () => import('@/views/outsourcedUnit/outsourcedUnitFileSearch') },
  threeViolation: { component: view.blank },
  threeViolationSubmit: { component: () => import('@/views/threeViolation/threeViolationSubmit') },
  ViolationProcessWrite: { component: () => import('@/views/threeViolation/ViolationProcessWrite') },
  safeFeedback: { component: () => import('@/views/threeViolation/safeFeedback') },
  checkFeedback: { component: () => import('@/views/threeViolation/checkFeedback') },
  leaderTalkFeedback: { component: () => import('@/views/threeViolation/leaderTalkFeedback') },
  familyFeedback: { component: () => import('@/views/threeViolation/familyFeedback') },
  closePassRecord: { component: () => import('@/views/threeViolation/closePassRecord') },
  passRecordCheck: { component: () => import('@/views/threeViolation/passRecordCheck') },
  performance: { component: view.blank },
  performanceManage: { component: () => import('@/views/performance/performanceManage') },
  performanceMaintain: { component: () => import('@/views/performance/performanceMaintain') },
  performanceSearch: { component: () => import('@/views/performance/performanceSearch') },
  riskCheck: { component: view.blank },
  riskCheckStandard: { component: () => import('@/views/riskCheck/riskCheckStandard') },
  riskCheckRecord: { component: () => import('@/views/riskCheck/riskCheckRecord') },
  riskCheckHistory: { component: () => import('@/views/riskCheck/riskCheckHistory') },
  riskCheckStatistics: { component: () => import('@/views/riskCheck/riskCheckStatistics') },
  hiddenDanger: { component: view.blank },
  hiddenDangerRecord: { component: () => import('@/views/hiddenDanger/hiddenDangerRecord') },
  hiddenDangerStatistics: { component: () => import('@/views/hiddenDanger/hiddenDangerStatistics') },
  protectionFacility: { component: view.blank },
  protectionFile: { component: () => import('@/views/protectionFacility/protectionFile') },
  facilityCheckRecord: { component: () => import('@/views/protectionFacility/facilityCheckRecord') },
  emergencyPlan: { component: view.blank },
  maintainEmergencyPlan: { component: () => import('@/views/emergencyPlan/maintainEmergencyPlan') },
  searchEmergencyPlan: { component: () => import('@/views/emergencyPlan/searchEmergencyPlan') },
  safetyTraining: { component: view.blank },
  safetyTrainingRecord: { component: () => import('@/views/safetyTraining/safetyTrainingRecord') },
  safetyTrainingSearch: { component: () => import('@/views/safetyTraining/safetyTrainingSearch') },
  specialEquipment: { component: view.blank },
  specialEquipmentMaintain: { component: () => import('@/views/specialEquipment/specialEquipmentMaintain') },
  specialEquipmentSearch: { component: () => import('@/views/specialEquipment/specialEquipmentSearch') },
  health: { component: view.blank },
  healthMaintain: { component: () => import('@/views/health/healthMaintain') },
  healthSearch: { component: () => import('@/views/health/healthSearch') },
  safeCheck: { component: view.blank },
  safeCheckMaintain: { component: () => import('@/views/safeCheck/safeCheckMaintain') },
  safeCheckSearch: { component: () => import('@/views/safeCheck/safeCheckSearch') },
  safeAccident: { component: view.blank },
  safeAccidentMaintain: { component: () => import('@/views/safeAccident/safeAccidentMaintain') },
  safeAccidentSearch: { component: () => import('@/views/safeAccident/safeAccidentSearch') },
  basic: { component: view.blank },
  module: { component: () => import('@/views/basic/module') },
  branch: { component: () => import('@/views/basic/branch') },
  workshop: { component: () => import('@/views/basic/workshop') },
  role: { component: () => import('@/views/basic/role') },
  dictionaries: { component: () => import('@/views/basic/dictionaries') },
  hiddenDangerType: { component: () => import('@/views/basic/hiddenDangerType') }
}
export default routerMap
